### ISSUE TITLE
"Normalize Indent on Paste" does not normalize indent on paste.

### ISSUE THREAD

**Issue by NatalieWolfe** [atom/settings-view#110]
In fact it does the opposite.

![normalize](https://cloud.githubusercontent.com/assets/466761/2715043/e7b165c2-c502-11e3-871d-fcf75e1854ae.gif)

I would have expected the pastes when "Normalize Indent on Paste" is on to be aligned with the other function definitions, but they are instead *always* inserted at column 1.

**Comment by jerone** [comment]
Is this option still available, because I can't find it in Settings > Settings > Editor Settings ?

**Comment by NatalieWolfe** [comment]
I think the name of the option changed to "Auto Indent On Paste" and is now fixed, hooray!

![autoindent](https://cloud.githubusercontent.com/assets/466761/5765456/89cf06d8-9cae-11e4-994d-44a8567fbdf3.gif)

**Comment by jlord** [comment]
Yep, looks good now :sparkles:

**Comment by jerone** [comment]
[**@NatalieWolfe**](https://github.com/NatalieWolfe) commented on [15 jan. 2015 21:04 CET](https://github.com/atom/settings-view/issues/110#issuecomment-70151909 "2015-01-15T20:04:31Z - Replied by Github Comment Enhancer"):
> I think the name of the option changed to "Auto Indent On Paste" and is now fixed, hooray!

I still see this option for some language grammars. For example [language-jade](https://github.com/devongovett/atom-jade) and [language-sln](https://github.com/rzhw/language-sln). Is this an issue for here or an issue for those packages? The option also appears as an text field, instead of the previously used checkbox.

![normalize indent on paste](https://cloud.githubusercontent.com/assets/55841/6854629/c1f069e6-d3f2-11e4-8bbd-31d76c5b1713.png)

**Comment by NatalieWolfe** [comment]
If the option is in the settings for those language packages, then you should probably report the issue on those packages.

**Comment by polarathene** [comment]
Is there a way to get it so pasting code where the cursor is already indented rather than at the start of the line works in the same way? 

I was 2 indents in, pasted 3 lines with no indentation and the next 2 lines started at the start of a line rather than keeping consistent indent level. If I remove the current indent so the cursor is at the start of the line prior to the paste, code is indented consistently at 2 indents in.

**Comment by ilyashubin** [comment]
@polarathene +1, always causing frustration
